module.exports = {
  core: [
    "arcade/arcade.js",
    "archive/archive.js",
    "blackjack/blackjack.js",
    "chat/chat.js",
    "chess/chess.js",
    "encrypt/encrypt.js",
    "explorer/explorer.js",
    //    'myqrcode/myqrcode.js',
    "poker/poker.js",
    // 'post/post.js',
    "qrscanner/qrscanner.js",
    "relay/relay.js",
    "redsquare/redsquare.js",
    "registry/registry.js",
    "saitolicious/saitolicious.js",
    "settings/settings.js",
    "settlers/settlers.js",
    "solitrio/solitrio.js",
    "wordblocks/wordblocks.js",
    //    'calendar/calendar.js',
    "website/website.js",
    "stun/stun.js",
    //    'video/video.js',
  ],
  lite: [
    "arcade/arcade.js",
    "archive/archive.js",
    "blackjack/blackjack.js",
    "chess/chess.js",
    "chat/chat.js",
    "debug/debug.js",
    "encrypt/encrypt.js",
    //    'myqrcode/myqrcode.js',
    "qrscanner/qrscanner.js",
    "poker/poker.js",
    //    'post/post.js',
    "redsquare/redsquare.js",
    "relay/relay.js",
    "registry/registry.js",
    "saitolicious/saitolicious.js",
    "settings/settings.js",
    //    'email/email.js',
    "settlers/settlers.js",
    "solitrio/solitrio.js",
    "wordblocks/wordblocks.js",
    //    'calendar/calendar.js',
    "website/website.js",
    "stun/stun.js",
    //  'video/video.js',
  ],
};
