module.exports = (app, mod, build_number) => {

  return `
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="${mod.description}">
    <title>Saito Explorer</title>

    <link rel="stylesheet" type="text/css" href="/saito/css-imports/saito-variables.css" />
    <!-- Load the bundled CSS generated by webpack -->
    <link rel="stylesheet" type="text/css" href="/${mod.name}/style.css" /> 
    
    <link rel="icon" media="(prefers-color-scheme: light)" href="/saito/img/favicon.svg" type="image/svg+xml" />
    <link rel="icon" media="(prefers-color-scheme: dark)" href="/saito/img/favicon-dark.svg" type="image/svg+xml" />
  </head>
  <body>
    <!-- The React app will mount into this div -->
    <div id="saito-react-app"></div>

    <!-- Load the core Saito library (optional, depending on build/environment) -->
    <script type="text/javascript" src="/saito/saito.js"></script>

    <!-- 
      bundle.js is not loaded here. React rendering is initiated directly 
      by explorerc.js's render() method, assuming components are compiled 
      into saito.js by the central build process.
    -->

  </body>
  </html>
  `;

} 