name: Playwright Tests
on:
  push:
    branches: [ main, master, feature/e2e-testing ]
  pull_request:
    branches: [ main, master, feature/e2e-testing]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install root dependencies
      run: npm ci
    - name: Deploy Application
      run: npm run go
    - name: Install test dependencies
      run: npm ci
      working-directory: tests
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: tests
    - name: Start Application
      run: npm start
    - name: Run Playwright tests
      run: npx playwright test
      working-directory: tests
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
